# Generated by Django 3.1.1 on 2021-02-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='age',
            new_name='institution',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gender',
        ),
    ]
