# Generated by Django 3.1.1 on 2021-02-22 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0004_auto_20210222_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='institution',
            new_name='insitution',
        ),
    ]
